name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: |
          make install
          make build-ts

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
