name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build
        run: npm i && npm run build

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
