name: Test push

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.ts"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint and format
        run: |
          make install
          make lint

      - name: Test
        run: make test-ci
