name: Test push

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.ts"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Lint and format
        run: npm i && npm run lint && npm run format:check && npm run build

      - name: Test
        run: npm test
